//
// Aster Communications Inc.
//
// Copyright (c) 2026 Aster Communications Inc.
//
// This file is part of this project.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//

package org.astermail.android.mail

val ASTER_DOMAIN_SUFFIXES: Set<String> = setOf(
    "astermail.org",
    "aster.cx",
)

val SOCIAL_DOMAIN_SUFFIXES: Set<String> = setOf(
    "facebook.com",
    "facebookmail.com",
    "fb.com",
    "messenger.com",
    "instagram.com",
    "linkedin.com",
    "twitter.com",
    "x.com",
    "reddit.com",
    "redditmail.com",
    "tiktok.com",
    "bytedance.com",
    "youtube.com",
    "pinterest.com",
    "discord.com",
    "discordapp.com",
    "snapchat.com",
    "quora.com",
    "meetup.com",
    "nextdoor.com",
    "tumblr.com",
    "twitch.tv",
    "mastodon.social",
    "bsky.app",
    "threads.net",
    "whatsapp.com",
    "telegram.org",
    "vk.com",
    "weibo.com",
    "line.me",
    "vimeo.com",
    "flickr.com",
    "deviantart.com",
    "behance.net",
    "dribbble.com",
    "goodreads.com",
    "strava.com",
    "patreon.com",
    "medium.com",
    "xing.com",
    "soundcloud.com",
    "last.fm",
    "untappd.com",
    "tinder.com",
    "bumble.com",
    "hinge.co",
    "tagged.com",
    "myspace.com",
)

val FORUM_DOMAIN_SUFFIXES: Set<String> = setOf(
    "googlegroups.com",
    "groups.io",
    "discourse.org",
    "discoursemail.com",
    "listserv.com",
    "freelists.org",
    "yahoogroups.com",
    "python.org",
    "sourceforge.net",
    "narkive.com",
    "librelist.com",
    "mailman3.com",
    "stackexchange.com",
    "stackoverflow.email",
    "stackoverflow.com",
)

val UPDATES_DOMAIN_SUFFIXES: Set<String> = setOf(
    "paypal.com",
    "stripe.com",
    "squareup.com",
    "venmo.com",
    "cash.app",
    "wise.com",
    "transferwise.com",
    "revolut.com",
    "coinbase.com",
    "kraken.com",
    "robinhood.com",
    "chime.com",
    "plaid.com",
    "intuit.com",
    "quickbooks.com",
    "chase.com",
    "bankofamerica.com",
    "wellsfargo.com",
    "citi.com",
    "citibank.com",
    "capitalone.com",
    "americanexpress.com",
    "aexp.com",
    "discover.com",
    "usbank.com",
    "pnc.com",
    "hsbc.com",
    "barclays.com",
    "ups.com",
    "fedex.com",
    "usps.com",
    "dhl.com",
    "ontrac.com",
    "canadapost.ca",
    "royalmail.com",
    "auspost.com.au",
    "purolator.com",
    "amazon.com",
    "ebay.com",
    "etsy.com",
    "walmart.com",
    "target.com",
    "bestbuy.com",
    "costco.com",
    "aliexpress.com",
    "wayfair.com",
    "uber.com",
    "ubereats.com",
    "lyft.com",
    "doordash.com",
    "grubhub.com",
    "instacart.com",
    "airbnb.com",
    "booking.com",
    "expedia.com",
    "hotels.com",
    "marriott.com",
    "hilton.com",
    "delta.com",
    "united.com",
    "aa.com",
    "southwest.com",
    "github.com",
    "gitlab.com",
    "atlassian.net",
    "npmjs.com",
    "vercel.com",
    "netlify.com",
    "cloudflare.com",
    "digitalocean.com",
    "heroku.com",
    "docker.com",
    "pypi.org",
    "jetbrains.com",
    "apple.com",
    "microsoft.com",
    "dropbox.com",
    "box.com",
    "notion.so",
    "zoom.us",
    "calendly.com",
    "docusign.net",
    "docusign.com",
    "slack.com",
    "asana.com",
    "trello.com",
    "okta.com",
    "auth0.com",
    "duosecurity.com",
    "1password.com",
    "dashlane.com",
    "verizon.com",
    "att.com",
    "t-mobile.com",
    "comcast.com",
    "xfinity.com",
)

val MARKETING_DOMAIN_SUFFIXES: Set<String> = setOf(
    "mcsv.net",
    "mcdlv.net",
    "rsgsv.net",
    "mailchimpapp.com",
    "mcsignup.com",
    "mctxapp.net",
    "list-manage.com",
    "klaviyomail.com",
    "kmail-lists.com",
    "klclick.com",
    "klaviyo.com",
    "rs6.net",
    "constantcontact.com",
    "hubspotemail.net",
    "hs-send.com",
    "mktomail.com",
    "mktdns.com",
    "createsend.com",
    "createsend1.com",
    "cmail19.com",
    "cmail20.com",
    "getresponse.com",
    "gr-message.com",
    "aweber.com",
    "activehosted.com",
    "sendinblue.com",
    "sibautomation.com",
    "omnisend.com",
    "getdrip.com",
    "exct.net",
    "exacttarget.com",
    "sailthru.com",
    "iterable.com",
    "braze.com",
    "mailerlite.com",
    "ml-attach.com",
    "convertkit.com",
    "ck.page",
)

val BULK_INFRA_DOMAIN_SUFFIXES: Set<String> = setOf(
    "sendgrid.net",
    "sendgrid.com",
    "mailgun.org",
    "mailgun.net",
    "amazonses.com",
    "sparkpostmail.com",
    "postmarkapp.com",
    "mtasv.net",
    "mailjet.com",
    "mandrillapp.com",
    "socketlabs.com",
    "pepipost.com",
    "elasticemail.com",
)

val BULK_SENDER_LOCALPARTS: Set<String> = setOf(
    "no-reply",
    "noreply",
    "no.reply",
    "noreplies",
    "donotreply",
    "do-not-reply",
    "do_not_reply",
    "notifications",
    "notification",
    "notify",
    "updates",
    "update",
    "alerts",
    "alert",
    "info",
    "news",
    "newsletter",
    "newsletters",
    "marketing",
    "offers",
    "deals",
    "promo",
    "promotions",
    "hello",
    "hi",
    "team",
    "support",
    "help",
    "contact",
    "mailer",
    "mailer-daemon",
    "bounce",
    "bounces",
    "receipts",
    "receipt",
    "billing",
    "invoice",
    "invoices",
    "account",
    "accounts",
    "members",
    "member",
    "community",
    "digest",
    "auto",
    "automated",
    "system",
    "service",
    "services",
    "email",
    "mail",
    "post",
    "messages",
    "reply",
    "store",
    "shop",
    "orders",
    "order",
    "confirm",
    "confirmation",
    "security",
)

val PROMOTIONS_SUBJECT_PATTERNS: List<Regex> = listOf(
    Regex("""\b\d{1,3}\s*%\s*off\b""", RegexOption.IGNORE_CASE),
    Regex("""\b\d{1,3}\s*%\s*(?:back|cash\s*back)\b""", RegexOption.IGNORE_CASE),
    Regex("""\bsale\b""", RegexOption.IGNORE_CASE),
    Regex("""\bdeal(s)?\b""", RegexOption.IGNORE_CASE),
    Regex("""\bdiscount(s)?\b""", RegexOption.IGNORE_CASE),
    Regex("""\bcoupon(s)?\b""", RegexOption.IGNORE_CASE),
    Regex("""\bpromo(?:\s*code)?\b""", RegexOption.IGNORE_CASE),
    Regex("""\boffer(s)?\b""", RegexOption.IGNORE_CASE),
    Regex("""\bsave\s+(?:up\s+to\s+)?\$?\d""", RegexOption.IGNORE_CASE),
    Regex("""\blimited\s+time\b""", RegexOption.IGNORE_CASE),
    Regex("""\bblack\s+friday\b""", RegexOption.IGNORE_CASE),
    Regex("""\bcyber\s+monday\b""", RegexOption.IGNORE_CASE),
    Regex("""\bflash\s+sale\b""", RegexOption.IGNORE_CASE),
    Regex("""\bfree\s+shipping\b""", RegexOption.IGNORE_CASE),
    Regex("""\bnew\s+arrivals?\b""", RegexOption.IGNORE_CASE),
    Regex("""\bexclusive\b""", RegexOption.IGNORE_CASE),
    Regex("""\bclearance\b""", RegexOption.IGNORE_CASE),
    Regex("""\bdon'?t\s+miss\b""", RegexOption.IGNORE_CASE),
    Regex("""\blast\s+chance\b""", RegexOption.IGNORE_CASE),
    Regex("""\bact\s+now\b""", RegexOption.IGNORE_CASE),
    Regex("""\bshop\s+now\b""", RegexOption.IGNORE_CASE),
    Regex("""\bbuy\s+(?:now|one)\b""", RegexOption.IGNORE_CASE),
    Regex("""\bbogo\b""", RegexOption.IGNORE_CASE),
    Regex("""\bmembers?\s+only\b""", RegexOption.IGNORE_CASE),
    Regex("""\bearly\s+access\b""", RegexOption.IGNORE_CASE),
    Regex("""\bgiveaway\b""", RegexOption.IGNORE_CASE),
    Regex("""\bbest\s+(?:price|deal)\b""", RegexOption.IGNORE_CASE),
    Regex("""\blowest\s+price\b""", RegexOption.IGNORE_CASE),
    Regex("""\bhot\s+deal\b""", RegexOption.IGNORE_CASE),
    Regex("""\btoday\s+only\b""", RegexOption.IGNORE_CASE),
    Regex("""\bends\s+(?:tonight|soon|today)\b""", RegexOption.IGNORE_CASE),
    Regex("""\bweekend\s+sale\b""", RegexOption.IGNORE_CASE),
    Regex("""\bsubscribe\s+and\s+save\b""", RegexOption.IGNORE_CASE),
    Regex("""[\x{1F300}-\x{1FAFF}]"""),
)

val UPDATES_SUBJECT_PATTERNS: List<Regex> = listOf(
    Regex("""\border(?:\s*#|\s+(?:confirm|number|placed|update))""", RegexOption.IGNORE_CASE),
    Regex("""\byour\s+order\b""", RegexOption.IGNORE_CASE),
    Regex("""\breceipt\b""", RegexOption.IGNORE_CASE),
    Regex("""\binvoice\b""", RegexOption.IGNORE_CASE),
    Regex("""\bpayment\b""", RegexOption.IGNORE_CASE),
    Regex("""\bshipped\b""", RegexOption.IGNORE_CASE),
    Regex("""\bshipping\b""", RegexOption.IGNORE_CASE),
    Regex("""\bout\s+for\s+delivery\b""", RegexOption.IGNORE_CASE),
    Regex("""\bdelivered\b""", RegexOption.IGNORE_CASE),
    Regex("""\bdelivery\b""", RegexOption.IGNORE_CASE),
    Regex("""\btracking\b""", RegexOption.IGNORE_CASE),
    Regex("""\bconfirm(ation|ed)?\b""", RegexOption.IGNORE_CASE),
    Regex("""\bbooking\b""", RegexOption.IGNORE_CASE),
    Regex("""\breservation\b""", RegexOption.IGNORE_CASE),
    Regex("""\bitinerary\b""", RegexOption.IGNORE_CASE),
    Regex("""\bboarding\s+pass\b""", RegexOption.IGNORE_CASE),
    Regex("""\bcheck[\s-]?in\b""", RegexOption.IGNORE_CASE),
    Regex("""\bappointment\b""", RegexOption.IGNORE_CASE),
    Regex("""\bstatement\b""", RegexOption.IGNORE_CASE),
    Regex("""\brenewal\b""", RegexOption.IGNORE_CASE),
    Regex("""\bsecurity\s+(?:alert|code|notification)\b""", RegexOption.IGNORE_CASE),
    Regex("""\bnew\s+(?:sign[\s-]?in|login|device)\b""", RegexOption.IGNORE_CASE),
    Regex("""\bverif(?:y|ication)\b""", RegexOption.IGNORE_CASE),
    Regex("""\bone[\s-]?time\s+(?:code|password|passcode)\b""", RegexOption.IGNORE_CASE),
    Regex("""\botp\b""", RegexOption.IGNORE_CASE),
    Regex("""\byour\s+code\s+is\b""", RegexOption.IGNORE_CASE),
    Regex("""\bpassword\s+(?:reset|changed)\b""", RegexOption.IGNORE_CASE),
    Regex("""\b2fa\b""", RegexOption.IGNORE_CASE),
    Regex("""\bsign[\s-]?in\b""", RegexOption.IGNORE_CASE),
)
